IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
             WHERE TABLE_NAME = 'DB_VERSION')
	AND 
	NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
             WHERE TABLE_NAME = 'DDB_VERSION')
			 )
BEGIN
  exec sp_rename 'DB_VERSION', 'DDB_VERSION'
END
