INSERT INTO [AUTH_FUNCTIONALITY] VALUES
('configurations', NULL),
('app', NULL),
('nodes', NULL)


UPDATE [AUTH_FUNCTIONALITY]
SET PARENT_FUNCT_ID = q.FUNCT_ID
FROM(	SELECT FUNCT_ID
		FROM [AUTH_FUNCTIONALITY]
		WHERE FUNCT_NAME = 'configurations')q
WHERE FUNCT_NAME IN ('app', 'nodes')