SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[DELETE_LOCAL_CODES]
	@p_map_set_id bigint
AS
BEGIN
	DELETE i
	FROM LOCAL_CODE lc
	INNER JOIN DATASET_COLUMN col on lc.COLUMN_ID = col.COL_ID
	INNER JOIN MAPPING_SET ms on ms.DS_ID = col.DS_ID
	INNER JOIN ITEM i on lc.LCD_ID = i.ITEM_ID
	WHERE ms.MAP_SET_ID = @p_map_set_id
END

GO